In [1]:
import pandas as pd
import numpy as np
from io import StringIO
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle
import warnings
warnings.filterwarnings("ignore")

In [2]:
with open('u.data', 'r') as file:
    data = file.read()

column_names = ['UserID', 'ItemID', 'Rating', 'Timestamp']
data = pd.read_csv(StringIO(data), sep="\t", header=None, names=column_names)

In [3]:
with open('u.item', 'r') as file:
     item = file.read()
column_names = ['ItemID','Title','Release_Date','Video_R_Date','IMDB_URL','Unknown','Action','Adventure','Animation',"Children\'s", 'Comedy','Crime','Documentary', 'Drama', 'Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western' ]
item = pd.read_csv(StringIO(item), sep="|", header=None, names=column_names)

In [4]:
with open('u.user', 'r') as file:
     user= file.read()
column_names = [ 'UserID','Age', 'Gender','Occupation','Zipcode' ]
user = pd.read_csv(StringIO(user), sep="|", header=None, names=column_names)

In [5]:
item.drop(columns = ["Video_R_Date","IMDB_URL"],inplace = True)

In [6]:
item

,ItemID,Title,Release_Date,Unknown,Action,Adventure,Animation,Children's,Comedy,Crime,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df1 =  pd.merge(item, data, on='ItemID', how='inner')

In [8]:
df1

,ItemID,Title,Release_Date,Unknown,Action,Adventure,Animation,Children's,Comedy,Crime,...,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,UserID,Rating,Timestamp
0,1,Toy Story (1995),01-Jan-1995,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,308,4,887736532
1,1,Toy Story (1995),01-Jan-1995,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,287,5,875334088
2,1,Toy Story (1995),01-Jan-1995,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,148,4,877019411
3,1,Toy Story (1995),01-Jan-1995,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,280,4,891700426
4,1,Toy Story (1995),01-Jan-1995,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,66,3,883601324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1678,Mat' i syn (1997),06-Feb-1998,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,863,1,889289570
99996,1679,B. Monkey (1998),06-Feb-1998,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,863,3,889289491
99997,1680,Sliding Doors (1998),01-Jan-1998,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,863,2,889289570
99998,1681,You So Crazy (1994),01-Jan-1994,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,896,3,887160722
99999,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,916,3,880845755

In [9]:
df =  pd.merge(df1, user , on='UserID', how='inner')

In [10]:
df['Rated_Date'] = pd.to_datetime(df['Timestamp'], unit='s')

In [11]:
df = df[["UserID",'ItemID','Title','Release_Date', 'Rating' ,'Rated_Date','Age','Gender','Occupation','Unknown', 'Action', 'Adventure',
       'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama','Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western',]]

In [12]:
df

,UserID,ItemID,Title,Release_Date,Rating,Rated_Date,Age,Gender,Occupation,Unknown,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,308,1,Toy Story (1995),01-Jan-1995,4,1998-02-17 17:28:52,60,M,retired,0,...,0,0,0,0,0,0,0,0,0,0
1,308,4,Get Shorty (1995),01-Jan-1995,5,1998-02-17 17:51:30,60,M,retired,0,...,0,0,0,0,0,0,0,0,0,0
2,308,5,Copycat (1995),01-Jan-1995,4,1998-02-17 18:20:08,60,M,retired,0,...,0,0,0,0,0,0,0,1,0,0
3,308,7,Twelve Monkeys (1995),01-Jan-1995,4,1998-02-17 18:07:27,60,M,retired,0,...,0,0,0,0,0,0,1,0,0,0
4,308,8,Babe (1995),01-Jan-1995,5,1998-02-17 17:31:36,60,M,retired,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,729,748,"Saint, The (1997)",14-Mar-1997,4,1998-04-22 23:10:38,19,M,student,0,...,0,0,0,0,0,1,0,1,0,0
99996,729,751,Tomorrow Never Dies (1997),01-Jan-1997,3,1998-04-22 23:05:38,19,M,student,0,...,0,0,0,0,0,1,0,1,0,0
99997,729,879,"Peacemaker, The (1997)",01-Jan-1997,3,1998-04-22 23:04:59,19,M,student,0,...,0,0,0,0,0,0,0,1,1,0
99998,729,894,Home Alone 3 (1997),01-Jan-1997,1,1998-04-22 23:08:31,19,M,student,0,...,0,0,0,0,0,0,0,0,0,0
99999,729,901,Mr. Magoo (1997),25-Dec-1997,1,1998-04-22 23:08:11,19,M,student,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
df['Release_Date'].fillna('25-Sep-1997', inplace=True)

In [14]:
df['Release_Date'] = pd.to_datetime(df['Release_Date'], format='%d-%b-%Y')

In [15]:
df['Diff_Date'] = (df['Rated_Date'] - df['Release_Date']).dt.days

In [16]:
df['Release_Year'] = df['Release_Date'].dt.year

In [17]:
df['Rated_Year'] = df['Rated_Date'].dt.year

In [18]:
average_rating_per_user = df.groupby('UserID')['Rating'].mean().reset_index()
average_rating_per_user.columns = ['UserID', 'average_user_rating']

df = df.merge(average_rating_per_user, on='UserID', how='left')

In [19]:
average_rating_per_movie = df.groupby('ItemID')['Rating'].mean().reset_index()
average_rating_per_movie.columns = ['ItemID', 'average_movie_rating']

df = df.merge(average_rating_per_movie, on='ItemID', how='left')

In [20]:
df = df[df['Diff_Date'] >= 0]

In [21]:
df

,UserID,ItemID,Title,Release_Date,Rating,Rated_Date,Age,Gender,Occupation,Unknown,...,Romance,Sci-Fi,Thriller,War,Western,Diff_Date,Release_Year,Rated_Year,average_user_rating,average_movie_rating
0,308,1,Toy Story (1995),1995-01-01,4,1998-02-17 17:28:52,60,M,retired,0,...,0,0,0,0,0,1143,1995,1998,3.758186,3.878319
1,308,4,Get Shorty (1995),1995-01-01,5,1998-02-17 17:51:30,60,M,retired,0,...,0,0,0,0,0,1143,1995,1998,3.758186,3.550239
2,308,5,Copycat (1995),1995-01-01,4,1998-02-17 18:20:08,60,M,retired,0,...,0,0,1,0,0,1143,1995,1998,3.758186,3.302326
3,308,7,Twelve Monkeys (1995),1995-01-01,4,1998-02-17 18:07:27,60,M,retired,0,...,0,1,0,0,0,1143,1995,1998,3.758186,3.798469
4,308,8,Babe (1995),1995-01-01,5,1998-02-17 17:31:36,60,M,retired,0,...,0,0,0,0,0,1143,1995,1998,3.758186,3.995434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,729,748,"Saint, The (1997)",1997-03-14,4,1998-04-22 23:10:38,19,M,student,0,...,1,0,1,0,0,404,1997,1998,2.857143,3.123418
99996,729,751,Tomorrow Never Dies (1997),1997-01-01,3,1998-04-22 23:05:38,19,M,student,0,...,1,0,1,0,0,476,1997,1998,2.857143,3.427778
99997,729,879,"Peacemaker, The (1997)",1997-01-01,3,1998-04-22 23:04:59,19,M,student,0,...,0,0,1,1,0,476,1997,1998,2.857143,3.272059
99998,729,894,Home Alone 3 (1997),1997-01-01,1,1998-04-22 23:08:31,19,M,student,0,...,0,0,0,0,0,476,1997,1998,2.857143,1.894737
99999,729,901,Mr. Magoo (1997),1997-12-25,1,1998-04-22 23:08:11,19,M,student,0,...,0,0,0,0,0,118,1997,1998,2.857143,1.916667

In [22]:
df_reduced = df[['UserID', 'ItemID', 'Rating',
       'Release_Year','Rated_Year','average_movie_rating','average_user_rating']]

In [23]:
from sklearn.decomposition import PCA

binary_columns = df[['Unknown', 'Action',
       'Adventure', 'Animation', 'Children\'s', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]
pca = PCA(n_components=5, random_state=42)  
binary_pca = pca.fit_transform(binary_columns)

binary_pca_df = pd.DataFrame(binary_pca, columns=[f"PCA_Binary_{i+1}" for i in range(binary_pca.shape[1])])

In [24]:
binary_pca_df.reset_index(drop=True, inplace=True)
df_reduced.reset_index(drop=True, inplace=True)

In [25]:
final_df = pd.concat([df_reduced,binary_pca_df], axis=1)

In [26]:
final_df

,UserID,ItemID,Rating,Release_Year,Rated_Year,average_movie_rating,average_user_rating,PCA_Binary_1,PCA_Binary_2,PCA_Binary_3,PCA_Binary_4,PCA_Binary_5
0,308,1,4,1995,1998,3.878319,3.758186,-0.167138,1.007304,0.235479,-0.500366,-0.508651
1,308,4,5,1995,1998,3.550239,3.758186,-0.119148,0.088845,-0.327436,-0.147232,0.872624
2,308,5,4,1995,1998,3.302326,3.758186,-0.280844,-0.781329,0.733927,0.194783,0.254002
3,308,7,4,1995,1998,3.798469,3.758186,-0.332834,-0.530026,-0.227317,-0.396789,0.046440
4,308,8,5,1995,1998,3.995434,3.758186,-0.737788,0.383654,-0.011962,-0.433489,0.069012
...,...,...,...,...,...,...,...,...,...,...,...,...
99764,729,748,4,1997,1998,3.123418,2.857143,0.818459,-0.236399,0.057266,1.073952,-0.166440
99765,729,751,3,1997,1998,3.427778,2.857143,0.818459,-0.236399,0.057266,1.073952,-0.166440
99766,729,879,3,1997,1998,3.272059,2.857143,0.929155,-0.425691,0.207186,0.318067,0.210851
99767,729,894,1,1997,1998,1.894737,2.857143,-0.164978,0.945160,0.193071,-0.379640,-0.204749
99768,729,901,1,1997,1998,1.916667,2.857143,-0.147774,0.836931,0.166795,-0.125079,0.266529

In [27]:
X = final_df[['UserID', 'ItemID','Release_Year','Rated_Year', 
        'average_movie_rating','average_user_rating','PCA_Binary_1',
       'PCA_Binary_2', 'PCA_Binary_3', 'PCA_Binary_4', 'PCA_Binary_5']]
y = final_df[['Rating']]

In [28]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [29]:
y['Rating'] = y['Rating']-1

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [31]:
xgb_model = XGBClassifier(use_label_encoder=False,max_depth=5, 
                          eval_metric="mlogloss", random_state=42)
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, objective='multi:softprob', ...)

In [32]:
genre_pca = final_df[['ItemID','Release_Year','PCA_Binary_1','PCA_Binary_2', 'PCA_Binary_3', 'PCA_Binary_4', 'PCA_Binary_5']]
genre_df = pd.merge(genre_pca, average_rating_per_movie, on='ItemID')

In [34]:
with open('xgb_model.pkl', 'wb') as f:
    pickle.dump(xgb_model, f)
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
with open('pca_model.pkl', 'wb') as file:
    pickle.dump(pca, file)
genre_df.drop_duplicates(inplace=True)
genre_df.reset_index(drop=True, inplace=True)
genre_df = genre_df[['ItemID', 'Release_Year','average_movie_rating' ,'PCA_Binary_1', 'PCA_Binary_2', 'PCA_Binary_3', 'PCA_Binary_4', 'PCA_Binary_5']]
genre_df.to_pickle("merged_movie_data.pkl")
avg_user = dict(zip(average_rating_per_user["UserID"], average_rating_per_user["average_user_rating"]))
with open("avg_user.pkl", "wb") as file:
    pickle.dump(avg_user, file)

In [35]:
genre = np.array([[0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0]])
pca_encoded = pca.transform(genre)

In [36]:
testing = np.array([[308,1,1995,1988,3.87,3.75]])
testing = np.concatenate((testing[:,[0,1,2,3,4,5]], pca_encoded ),axis =1)
testing = scaler.transform(testing)
result = xgb_model.predict(testing)
result[0]+1

4